# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d9d445a269f324ae0cd4ce89052766d42ada00fe0ab81a06c490f28d2a9e61bd79b906e8eda1c5058c7b557eac97c0535d91bbf0d05a519fc651d9755854960

test:
  secret_key_base: 4eb620efa92f6b75fcb4b69bfaf526d5a74ceed4814b9957ac4b96da5bd3cbd464e04b7f3e3c45485ec17c93725d298ecf835609cb1aab46277066e6e92c6147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
